파이썬 내장 함수
https://docs.python.org/ko/3/library/functions.html

* 현재 설치된 numpy 버전 확인

In [ ]:
!pip show numpy

Name: numpy
Version: 1.24.0
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: albumentations, altair, arviz, astropy, autograd, blis, bokeh, chex, cmdstanpy, contourpy, cufflinks, cvxpy, datascience, db-dtypes, dopamine-rl, ecos, flax, folium, gensim, gym, h5py, holoviews, hyperopt, imageio, imbalanced-learn, imgaug, jax, jaxlib, librosa, lightgbm, matplotlib, matplotlib-venn, missingno, mizani, ml-dtypes, mlxtend, moviepy, music21, nibabel, numba, numexpr, opencv-contrib-python, opencv-python, opencv-python-headless, opt-einsum, optax, orbax-checkpoint, osqp, pandas, pandas-gbq, patsy, plotnine, prophet, pyarrow, pycocotools, pyerfa, pymc, pytensor, python-louvain, PyWavelets, qdldl, qudida, scikit-image, scikit-learn, scipy, scs, seaborn, shapely, sklearn-pandas, soxr, spacy, statsmodels, tables, ten

* numpy 불러오기

In [ ]:
# import numpy
import numpy as np

* 패키지 정보 보기 help와 dir

In [ ]:
help(np)

In [ ]:
dir(np)

* iris 데이터셋 로드 예제

In [ ]:
from sklearn.datasets import load_iris
import sklearn.datasets

iris = load_iris()

In [ ]:
dir(sklearn.datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'data',
 'descr',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerb

* 데이터셋 출력

In [ ]:
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

* 데이터셋 세부정보 보기

In [ ]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

* 열머리글 정보와 해당 데이터 보기

In [ ]:
print(iris.feature_names)
print(iris.data[:10])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


* 라벨 정보와 데이터 보기

In [ ]:
print(iris.target_names)
print(iris.target)

['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


* 도준은 100, 50, 30의 재산을 가지고 있다. 리스트와 numpy array로 저장하고 데이터타입을 출력하여 비교

In [ ]:
dojun_list = [100, 50, 30]
# dojun_arr = np.array((100, 50, 30))
dojun_arr = np.array(dojun_list)
print(type(dojun_list))
print(type(dojun_arr))

<class 'list'>
<class 'numpy.ndarray'>


* 도준의 재산을 100, 50, 30<br>
성준의 재산을 200, 30, 80<br>
이라고 리스트로 저장한 후 더하기 연산하여 결과를 출력

In [ ]:
dojun_list = [100, 50, 30]
sungjun_list = [200, 30, 80]
total_list = dojun_list + sungjun_list
print(total_list)

[100, 50, 30, 200, 30, 80]


* 위 내용을 리스트 대신 numpy array로 저장하여 결과를 출력

In [ ]:
dojun_arr = np.array(dojun_list)
sungjun_arr = np.array(sungjun_list)
total_arr = dojun_arr + sungjun_arr
print(total_arr)

[300  80 110]


* 위위의 리스트에 곱하기 연산을 하여 결과를 출력

In [ ]:
# mult_list = dojun_list * sungjun_list
# print(mult_list)

* 위의 array에 곱하기 연산을 하여 결과를 출력

In [ ]:
mult_arr = dojun_arr * sungjun_arr
print(mult_arr)

[20000  1500  2400]


* 도준은 성준에 비해 몇%의 재산을 가지고 있는지 계산하고 출력. 위의 list 및 array는 2020년, 2021년, 2022년도의 재산을 나타냄

* 리스트

In [ ]:
for dojun, sungjun in zip(dojun_list, sungjun_list):
    rate = dojun / sungjun
    print(rate)

0.5
1.6666666666666667
0.375


* array

In [ ]:
dojun_arr / sungjun_arr

array([0.5       , 1.66666667, 0.375     ])

* 인덱싱과 슬라이싱

* 인덱싱

In [ ]:
dojun_arr[0]

100

In [ ]:
dojun_arr[-1]

30

* 슬라이싱

In [ ]:
dojun_arr[:]

array([100,  50,  30])

In [ ]:
dojun_arr[:2]

array([100,  50])

In [ ]:
dojun_arr[-2:]

array([50, 30])

* 2차원 배열 생성

In [ ]:
dojun_arr_a = np.array([(1,2,3), (4,5,6)])
dojun_arr_b = np.array([[1,2,3], [4,5,6]])
print(type(dojun_arr_a))
print(type(dojun_arr_b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


* 2차원 배열 인덱싱

In [ ]:
dojun_arr_a[0]

array([1, 2, 3])

In [ ]:
dojun_arr_a[0][1]

2

In [ ]:
type(dojun_arr_a[0][1])

numpy.int64

In [ ]:
dojun_arr_a[0][1] = 20
print(dojun_arr_a)

[[ 1 20  3]
 [ 4  5  6]]


* 2차원 배열 슬라이싱

In [ ]:
print(dojun_arr_a[:1])
print(dojun_arr_a[0])

[[ 1 20  3]]
[ 1 20  3]


* 두가지 배열의 형태

In [ ]:
print(dojun_arr_a[:1].shape)
print(dojun_arr_a[0].shape)

(1, 3)
(3,)


* 두가지 배열의 차원

In [ ]:
print(dojun_arr_a[:1].ndim)
print(dojun_arr_a[0].ndim)

2
1


* 슬라이싱 응용

In [ ]:
dojun_arr_a[:1][0]

array([ 1, 20,  3])

In [ ]:
dojun_arr_a[:1][0][:2]

array([ 1, 20])

In [ ]:
print(dojun_arr_a[:1][0][:1])
print(type(dojun_arr_a[:1][0][:1]))
print(dojun_arr_a[:1][0][0])
print(type(dojun_arr_a[:1][0][0]))
print(dojun_arr_a[:1][0][:1][0])
print(type(dojun_arr_a[:1][0][:1][0]))

[1]
<class 'numpy.ndarray'>
1
<class 'numpy.int64'>
1
<class 'numpy.int64'>


* 2중 슬라이싱

In [ ]:
arr = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])

In [ ]:
arr[:2]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
arr[:2, :2]

array([[10, 20],
       [50, 60]])

In [ ]:
arr[:2][:2]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
arr[:2, 1]

array([20, 60])

* 5이상의 값만 표시

In [ ]:
dojun_arr_a

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [ ]:
dojun_arr_a[dojun_arr_a>=5]

array([20,  5,  6])

In [ ]:
[dojun_arr_a>=5]

[array([[False,  True, False],
        [False,  True,  True]])]

* 텍스트가 포함된 array

In [ ]:
# dojun_arr_c = np.array([["1",2,3], [4,5,6]])
# dojun_arr_c / 5

* 3차원 배열

In [ ]:
dojun_arr_3d = np.array([[(1,2,3), (4,5,6)],[(7,8,9), (10,11,12)]])
print(type(dojun_arr_3d))

<class 'numpy.ndarray'>


* 배열의 길이 확인

In [ ]:
len(dojun_arr_3d)

2

* 배열의 차원 확인

In [ ]:
dojun_arr_3d.shape

(2, 2, 3)

In [ ]:
dojun_arr_3d.shape[0]

2

* 배열의 차원수 확인

In [ ]:
dojun_arr_3d.ndim

3

In [ ]:
len(dojun_arr_3d.shape)

3

* 전체 원소의 개수 확인

In [ ]:
dojun_arr_3d.size

12

* yejun_arr_2d라는 2차원 배열을 생성. 데이터타입을 float32로 지정

In [ ]:
yejun_arr_2d = np.array([[1,2,3], [4,5,6]], dtype=np.float32)
print(type(yejun_arr_2d))
print(yejun_arr_2d.dtype)

<class 'numpy.ndarray'>
float32


* 현재 dojun_arr_a 배열의 데이터타입을 출력한 후, 데이터타입을 float32로 변경하고 변경 후 데이터타입을 출력

In [ ]:
print(dojun_arr_a.dtype)
dojun_arr_a = dojun_arr_a.astype(np.float32)
print(dojun_arr_a.dtype)


int64
float32


* 다양한 기본형 array 만들기

* 모든 값이 0인 2차원배열(2X3) 만들기

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

* 모든 값이 1인 2차원배열(2X3) 만들기

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

* 모든 값이 10인 2차원배열(2X3) 만들기

In [ ]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

* 모든 값이 랜덤값인 2차원배열(2X3) 만들기

In [ ]:
np.random.random((2, 3))

array([[0.36517586, 0.52815645, 0.74490307],
       [0.16543269, 0.25452887, 0.57038742]])

* 배열의 계산

In [ ]:
arr = np.array([[1, 20, 3], [4, 5, 6]])
arr

array([[ 1, 20,  3],
       [ 4,  5,  6]])

* 배열의 합

In [ ]:
arr.sum()

39

* 배열의 최솟값, 최댓값

In [ ]:
arr.min()

1

In [ ]:
arr.max()

20

* 배열의 누적값

In [ ]:
arr.cumsum()

array([ 1, 21, 24, 28, 33, 39])

* 배열의 평균

In [ ]:
arr.mean()

6.5

* 배열 변형

* 배열 정렬

In [ ]:
np.sort(arr)

array([[ 1,  3, 20],
       [ 4,  5,  6]])

In [ ]:
-np.sort(-arr)

array([[20,  3,  1],
       [ 6,  5,  4]])

* 전치 행렬 : 행과 열 바꾸기

In [ ]:
arr.T

array([[ 1,  4],
       [20,  5],
       [ 3,  6]])

* 1차원으로 변경

In [ ]:
arr.ravel()

array([ 1, 20,  3,  4,  5,  6])

* 1차원 변경 후 전체 정렬

In [ ]:
np.sort(arr.ravel())
# cf) flatten

array([ 1,  3,  4,  5,  6, 20])

* 역순 정렬

In [ ]:
-np.sort(-arr.ravel())

array([20,  6,  5,  4,  3,  1])

* 배열의 차원과 형상 바꾸기

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.reshape(1,6)

array([[ 1, 20,  3,  4,  5,  6]])

In [ ]:
arr.reshape(1, -1)

array([[ 1, 20,  3,  4,  5,  6]])

In [ ]:
arr.reshape(2, -1)

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [ ]:
arr.reshape(6,1)

array([[ 1],
       [20],
       [ 3],
       [ 4],
       [ 5],
       [ 6]])

* 순차 배열 생성

In [ ]:
arr_a = np.arange(5)

In [ ]:
arr_a

array([0, 1, 2, 3, 4])

* 배열 붙이기

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
np.append(arr1, arr2)

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[7,8,9],[10,11,12]])

In [ ]:
np.append(arr3, arr4)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.concatenate([arr3, arr4], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([arr3, arr4], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

* 데이터 추가

In [ ]:
arr

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [ ]:
np.insert(arr, 3, 10)

array([ 1, 20,  3, 10,  4,  5,  6])

In [ ]:
np.insert(arr, 4, 10)

array([ 1, 20,  3,  4, 10,  5,  6])

* 데이터 삭제

In [ ]:
np.delete(arr, 2)

array([ 1, 20,  4,  5,  6])